   create table shop (
	id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        storeNumber     int not null,
        sitestatus      varchar(30),
        longitude       numeric(20,16) default 0.00,
        siteAddress     varchar(80),
	siteCity        varchar(40),
        siteDescription varchar(80),
        siteEmail       varchar(128),
        siteFax         varchar(20),
        sitePhone       varchar(20),
        changedDate     timestamp default now(),
	createdDate     timestamp default now(),
	timezone        varchar(30) default null,
        latitude        numeric(20,16) default 0.00,
        sitetype        varchar(30),
        shopName        varchar(100),
        highway         varchar(100),
        exitNumber      varchar(50),
        stateCd         char(02),
        sitezipcode     varchar(20),
        phone           varchar(20),
        division        int default 0,
        district        int default 0,
        companycode     int default 0,
        companydesc     varchar(30),
        isDeleted       char(01) default 'N',
        changedBy       varchar(30) default 'system'
    );
